/* SPDX-License-Identifier: GPL-2.0 */
/*
 * can_sdc - SUNIX SDC CAN FD controller driver
 *
 * Copyright (c) 2025 SUNIX Co., Ltd. <info@sunix.com>
 *
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
 *
 */
#ifndef _SDC_CANFD_H_
#define _SDC_CANFD_H_

#include <linux/can/core.h>
#include <linux/can/dev.h>
#include <linux/can/rx-offload.h>
#include <linux/kernel.h>

/* CAN FD Controller Module SFR */
/* CLOCK */
#define SDC_CANFD_SYS_CLK 62500000
#define SDC_CANFD_REF_CLK 80000000

/* CONTROL REGISTER */
#define SDC_CANFD_REG_CON 0x00
#define SDC_CANFD_REG_CON_MODE_REGISTER_MASK GENMASK(2, 0)
#define SDC_CANFD_REG_CON_MODE_CONFIG 0
#define SDC_CANFD_REG_CON_MODE_NORMAL 1
#define SDC_CANFD_REG_CON_MODE_LISTEN 2
#define SDC_CANFD_REG_CON_MODE_INTERNAL_LOOPBACK 4
#define SDC_CANFD_REG_CON_MODE_EXTERNAL_LOOPBACK 5
#define SDC_CANFD_REG_CON_TRIPLE_SAMPLE BIT(3)
#define SDC_CANFD_REG_CON_TERMINATION BIT(4)
#define SDC_CANFD_REG_CON_ISO11898_MODE BIT(5)
#define SDC_CANFD_REG_CON_TX_EVENT_QUEUE BIT(8)
#define SDC_CANFD_REG_CON_TRANSMIT_ESI_GW_MODE BIT(9)
#define SDC_CANFD_REG_CON_TX_TRANSMIT_INTERVAL_MASK GENMASK(31, 16)

/* INTERRUPT ENABLE REGISTER */
#define SDC_CANFD_REG_INT_ENABLE 0x01
#define SDC_CANFD_REG_INT_ENABLE_TX_RX_EVENT_QUEUE_MASK GENMASK(15, 0)
#define SDC_CANFD_REG_INT_ENABLE_TX_MSG_LOST_ARBITRATION BIT(16)
#define SDC_CANFD_REG_INT_ENABLE_MSG_ERROR_DETECTED BIT(17)
#define SDC_CANFD_REG_INT_ENABLE_TX_MSG_ATTEMPTS_EXHAUSTED BIT(18)
#define SDC_CANFD_REG_INT_ENABLE_BUS_STATE_CHANGE_EVENT BIT(24)
#define SDC_CANFD_REG_INT_ENABLE_TIME_STAMP_COUNTER_ROLLOVER BIT(25)
#define SDC_CANFD_REG_INT_ENABLE_ALL_MASK GENMASK(31, 0)

/* INTERRUPT STATUS REGISTER */
#define SDC_CANFD_REG_INT_STATUS 0x02
#define SDC_CANFD_REG_INT_STATUS_TX_RX_EVENT_QUEUE_MASK GENMASK(15, 0)
#define SDC_CANFD_REG_INT_STATUS_TX_MSG_QUEUE_EMPTY BIT(0)
#define SDC_CANFD_REG_INT_STATUS_TX_MSG_QUEUE_BELOW_TRIGGER_POS BIT(1)
#define SDC_CANFD_REG_INT_STATUS_TX_MSG_QUEUE_FULL BIT(2)
#define SDC_CANFD_REG_INT_STATUS_TX_MSG_QUEUE_OVERFLOW BIT(3)
#define SDC_CANFD_REG_INT_STATUS_TX_EVENT_QUEUE_NON_EMPTY BIT(4)
#define SDC_CANFD_REG_INT_STATUS_TX_EVENT_QUEUE_BELOW_TRIGGER_POS BIT(5)
#define SDC_CANFD_REG_INT_STATUS_TX_EVENT_QUEUE_FULL BIT(6)
#define SDC_CANFD_REG_INT_STATUS_TX_EVENT_QUEUE_OVERFLOW BIT(7)
#define SDC_CANFD_REG_INT_STATUS_RX_MSG_QUEUE_NON_EMPTY BIT(8)
#define SDC_CANFD_REG_INT_STATUS_RX_MSG_QUEUE_ABOVE_TRIGGER_POS BIT(9)
#define SDC_CANFD_REG_INT_STATUS_RX_MSG_QUEUE_FULL BIT(10)
#define SDC_CANFD_REG_INT_STATUS_RX_MSG_QUEUE_OVERFLOW BIT(11)
#define SDC_CANFD_REG_INT_STATUS_TX_EVENT_QUEUE_TIMEOUT BIT(12)
#define SDC_CANFD_REG_INT_STATUS_RX_MSG_QUEUE_TIMEOUT BIT(13)
#define SDC_CANFD_REG_INT_STATUS_TX_MSG_LOST_ARBITRATION BIT(16)
#define SDC_CANFD_REG_INT_STATUS_MSG_ERROR_DETECTED BIT(17)
#define SDC_CANFD_REG_INT_STATUS_TX_MSG_ATTEMPTS_EXHAUSTED BIT(18)
#define SDC_CANFD_REG_INT_STATUS_BUS_STATE_CHANGE_EVENT BIT(24)
#define SDC_CANFD_REG_INT_STATUS_TIME_STAMP_COUNTER_ROLLOVER BIT(25)
#define SDC_CANFD_REG_INT_STATUS_ALL_MASK GENMASK(31, 0)

/* NOMINAL BIT TIME REGISTER */
#define SDC_CANFD_REG_NOMINAL_BIT_TIME 0x04
#define SDC_CANFD_REG_NOMINAL_BRP_MASK GENMASK(7, 0)
#define SDC_CANFD_REG_NOMINAL_TSEG1_MASK GENMASK(15, 8)
#define SDC_CANFD_REG_NOMINAL_TSEG2_MASK GENMASK(23, 16)
#define SDC_CANFD_REG_NOMINAL_SJW_MASK GENMASK(31, 24)

/* DATA BIT TIME REGISTER */
#define SDC_CANFD_REG_DATA_BIT_TIME 0x05
#define SDC_CANFD_REG_DATA_BRP_MASK GENMASK(7, 0)
#define SDC_CANFD_REG_DATA_TSEG1_MASK GENMASK(13, 8)
#define SDC_CANFD_REG_DATA_TSEG2_MASK GENMASK(20, 16)
#define SDC_CANFD_REG_DATA_SJW_MASK GENMASK(28, 24)

/* FILTER CONTROL REGISTER */
#define SDC_CANFD_REG_FILTER_CON 0x07
#define SDC_CANFD_REG_FILTER_ENABLE_MASK GENMASK(31, 0)

/* TIME STAMP COUNTER CONTROL REGISTER */
#define SDC_CANFD_REG_TIME_STAMP_COUNTER_CON 0x08
#define SDC_CANFD_REG_TIME_STAMP_COUNTER_ENABLE BIT(0)
#define SDC_CANFD_REG_TIME_STAMP_CAPTURE_MASK GENMASK(2, 1)
#define SDC_CANFD_REG_TIME_STAMP_CAPTURE_START_OF_FRAME 1
#define SDC_CANFD_REG_TIME_STAMP_CAPTURE_END_OF_FRAME 2
#define SDC_CANFD_REG_TIME_STAMP_PRE_SCALAR_MASK GENMASK(31, 16)

/* CURRENT TIME STAMP REGISTER */
#define SDC_CANFD_REG_CURRENT_TIME_STAMP 0x09

/* TX ERROR COUNT / RX ERROR COUNT REGISTER */
#define SDC_CANFD_REG_TX_RX_ERROR_COUNT 0x0a
#define SDC_CANFD_REG_TX_ERROR_COUNT_MASK GENMASK(8, 0)
#define SDC_CANFD_REG_RX_ERROR_COUNT_MASK GENMASK(24, 16)

/* BUS DIAGNOSTIC REGISTER */
#define SDC_CANFD_REG_BUS_DIAGNOSTIC 0x0b
#define SDC_CANFD_REG_BUS_DIAGNOSTIC_RECV_CANFD_MSG_ESI_FLAG_SET BIT(16)
#define SDC_CANFD_REG_BUS_DIAGNOSTIC_TX_BIT_ERR BIT(17)
#define SDC_CANFD_REG_BUS_DIAGNOSTIC_TX_ACK_ERR BIT(18)
#define SDC_CANFD_REG_BUS_DIAGNOSTIC_RX_FORM_ERR BIT(19)
#define SDC_CANFD_REG_BUS_DIAGNOSTIC_RX_STUFF_ERR BIT(20)
#define SDC_CANFD_REG_BUS_DIAGNOSTIC_RX_CRC_ERR BIT(21)
#define SDC_CANFD_REG_BUS_DIAGNOSTIC_BUS_STATE_MASK GENMASK(23, 22)
#define SDC_CANFD_REG_BUS_STATE_ERROR_ACTIVE 0
#define SDC_CANFD_REG_BUS_STATE_ERROR_PASSIVE 1
#define SDC_CANFD_REG_BUS_STATE_ERROR_BUS_OFF 3

/* TX MESSAGE QUEUE STATUS REGISTER */
#define SDC_CANFD_REG_TX_MSG_QUEUE_STATUS 0x0d
#define SDC_CANFD_REG_TX_MSG_QUEUE_CURRENT_MSG_COUNT_MASK GENMASK(15, 0)
#define SDC_CANFD_REG_TX_MSG_QUEUE_CURRENT_DW_COUNT_MASK GENMASK(31, 16)

/* TX EVENT QUEUE STATUS REGISTER */
#define SDC_CANFD_REG_TX_EVENT_QUEUE_STATUS 0x0e
#define SDC_CANFD_REG_TX_EVENT_QUEUE_CURRENT_MSG_COUNT_MASK GENMASK(15, 0)

/* RX MESSAGE QUEUE STATUS REGISTER */
#define SDC_CANFD_REG_RX_MSG_QUEUE_STATUS 0x0f
#define SDC_CANFD_REG_RX_MSG_QUEUE_CURRENT_MSG_COUNT_MASK GENMASK(15, 0)
#define SDC_CANFD_REG_RX_MSG_QUEUE_CURRENT_DW_COUNT_MASK GENMASK(31, 16)

/* TX MESSAGE QUEUE CONTROL REGISTER */
#define SDC_CANFD_REG_TX_MSG_QUEUE_CON 0x20
#define SDC_CANFD_REG_TX_MSG_QUEUE_FLUSH_REQ BIT(0)
#define SDC_CANFD_REG_TX_MSG_RETRANS_ATTEMPT_CON_MASK GENMASK(5, 4)
#define SDC_CANFD_REG_TX_MSG_RETRANS_ATTEMPT_DISABLE 0
#define SDC_CANFD_REG_TX_MSG_RETRANS_ATTEMPT_3_TIMES 2
#define SDC_CANFD_REG_TX_MSG_RETRANS_ATTEMPT_UNLIMITED 3
#define SDC_CANFD_REG_TX_MSG_QUEUE_INT_TRIGGER_SOURCE BIT(8)
#define SDC_CANFD_REG_TX_MSG_QUEUE_INT_TRIGGER_POS_MASK GENMASK(31, 16)

/* TX MESSAGE CONTROL REGISTER */
#define SDC_CANFD_REG_TX_MSG_CON 0x21
#define SDC_CANFD_REG_TX_MSG_INCREASE_MSG_COUNT BIT(0)

/* TX FRAME CONTROL-0 REGISTER */
#define SDC_CANFD_REG_TX_FRAME_CON0 0x2e
#define SDC_CANFD_REG_TX_FRAME_DLC_MASK GENMASK(3, 0)
#define SDC_CANFD_REG_TX_FRAME_EXT_ID_ENABLE BIT(4)
#define SDC_CANFD_REG_TX_FRAME_RTR BIT(5)
#define SDC_CANFD_REG_TX_FRAME_BRS BIT(6)
#define SDC_CANFD_REG_TX_FRAME_FDF BIT(7)
#define SDC_CANFD_REG_TX_FRAME_ESI BIT(8)
#define SDC_CANFD_REG_TX_FRAME_SEQ_MASK GENMASK(31, 16)

/* TX FRAME CONTROL-1 REGISTER */
#define SDC_CANFD_REG_TX_FRAME_CON1 0x2f
#define SDC_CANFD_REG_TX_FRAME_EID_MASK GENMASK(28, 0)
#define SDC_CANFD_REG_TX_FRAME_SID_MASK GENMASK(10, 0)
/* EXT_ID ENABLE:29 bit, EXT_ID DISABLE:11 bit */

/* TX MESSAGE DW REGISTER */
/* 16DW, start from 0x30 to 0x3f */
#define SDC_CANFD_REG_TX_MSG_DW(x) (0x30 + (x))
#define SDC_CANFD_REG_TX_MSG_DW0 0x30

/* TX EVENT QUEUE CONTROL REGISTER */
#define SDC_CANFD_REG_TX_EVENT_QUEUE_CON 0x10
#define SDC_CANFD_REG_TX_EVENT_QUEUE_FLUSH_REQ BIT(0)
#define SDC_CANFD_REG_TX_EVENT_QUEUE_DECREASE_MSG_COUNT BIT(1)
#define SDC_CANFD_REG_TX_EVENT_QUEUE_INT_TRIGGER_SOURCE BIT(8)
#define SDC_CANFD_REG_TX_EVENT_QUEUE_INT_TRIGGER_POS_MASK GENMASK(31, 16)

/* TX EVENT DW-0 REGISTER */
#define SDC_CANFD_REG_TX_EVENT_DW0 0x11
#define SDC_CANFD_REG_TX_EVENT_DLC_MASK GENMASK(3, 0)
#define SDC_CANFD_REG_TX_EVENT_EXT_ID_ENABLE BIT(4)
#define SDC_CANFD_REG_TX_EVENT_RTR BIT(5)
#define SDC_CANFD_REG_TX_EVENT_BRS BIT(6)
#define SDC_CANFD_REG_TX_EVENT_FDF BIT(7)
#define SDC_CANFD_REG_TX_EVENT_ESI BIT(8)
#define SDC_CANFD_REG_TX_EVENT_SEQ_NUM_MASK GENMASK(31, 16)

/* TX EVENT DW-1 REGISTER */
#define SDC_CANFD_REG_TX_EVENT_DW1 0x12
#define SDC_CANFD_REG_TX_EVENT_EID_MASK GENMASK(28, 0)
#define SDC_CANFD_REG_TX_EVENT_SID_MASK GENMASK(10, 0)
/* EXT_ID ENABLE:29 bit, EXT_ID DISABLE:11 bit */

/* TX EVENT DW-2 REGISTER */
#define SDC_CANFD_REG_TX_EVENT_DW2 0x13
#define SDC_CANFD_REG_TX_EVENT_TIME_STAMP_MASK GENMASK(31, 0)

/* RX MESSAGE QUEUE CONTROL REGISTER */
#define SDC_CANFD_REG_RX_MSG_QUEUE_CON 0x40
#define SDC_CANFD_REG_RX_MSG_QUEUE_FLUSH_REQ BIT(0)
#define SDC_CANFD_REG_RX_MSG_QUEUE_INT_TRIGGER_SOURCE BIT(8)
#define SDC_CANFD_REG_RX_MSG_QUEUE_INT_TRIGGER_POS_MASK GENMASK(31, 16)

/* RX MESSAGE CONTROL REGISTER */
#define SDC_CANFD_REG_RX_MSG_CON 0x41
#define SDC_CANFD_REG_RX_MSG_DECREASE_MSG_COUNT BIT(0)

/* RX FRAME CONTROL-0 REGISTER */
#define SDC_CANFD_REG_RX_FRAME_CON0 0x4d
#define SDC_CANFD_REG_RX_FRAME_DLC_MASK GENMASK(3, 0)
#define SDC_CANFD_REG_RX_FRAME_EXT_ID_ENABLE BIT(4)
#define SDC_CANFD_REG_RX_FRAME_RTR BIT(5)
#define SDC_CANFD_REG_RX_FRAME_BRS BIT(6)
#define SDC_CANFD_REG_RX_FRAME_FDF BIT(7)
#define SDC_CANFD_REG_RX_FRAME_ESI BIT(8)
#define SDC_CANFD_REG_RX_FRAME_MATCHED_FILTER_ID_MASK GENMASK(15, 8)

/* RX FRAME CONTROL-1 REGISTER */
#define SDC_CANFD_REG_RX_FRAME_CON1 0x4e
#define SDC_CANFD_REG_RX_FRAME_EID_MASK GENMASK(28, 0)
#define SDC_CANFD_REG_RX_FRAME_SID_MASK GENMASK(10, 0)
/* EXT_ID ENABLE:29 bit, EXT_ID DISABLE:11 bit */

/* RX FRAME CONTROL-2 REGISTER */
#define SDC_CANFD_REG_RX_FRAME_CON2 0x4f
#define SDC_CANFD_REG_RX_FRAME_TIME_STAMP_MASK GENMASK(31, 0)

/* RX MESSAGE DW REGISTER */
/* 16DW, start from 0x50 to 0x5f */
#define SDC_CANFD_REG_RX_MSG_DW(x) (0x50 + (x))
#define SDC_CANFD_REG_RX_MSG_DW0 0x50

/* RX FILTER ID AND MASK REGISTER */
/* 32 groups, start from 0 to 31 */
#define SDC_CANFD_REG_FILTER_ID(x) (0x80 + 0x02 * (x))
#define SDC_CANFD_REG_FILTER_ID0  0x80
#define SDC_CANFD_REG_FILTER_MASK(x) (0x81 + 0x02 * (x))
#define SDC_CANFD_REG_FILTER_MASK0  0x81

#define SDC_CANFD_REG_FILTER_ID_MASK  GENMASK(28, 0)
#define SDC_CANFD_REG_FILTER_EXT_ID_ENABLE  BIT(31)
#define SDC_CANFD_REG_FILTER_MASK_MASK GENMASK(28, 0)

struct sdc_canfd_priv;
struct sdc_canfd_ops {
	/* Device specific call backs */
	u32 (*read_reg)(const struct sdc_canfd_priv *dev, int reg);
	int (*write_reg)(const struct sdc_canfd_priv *dev, int reg, int val);
};

struct sdc_canfd_priv {
	struct can_priv can;	/* must be first member! */
	struct can_rx_offload offload;
	struct net_device *ndev;
	void __iomem *base;
	int	base_size;
	void __iomem *event;
	unsigned int event_value;
	spinlock_t event_lock;

	unsigned int tx_head;
	unsigned int tx_tail;
	spinlock_t tx_lock;

	struct can_berr_counter bec;

	struct sdc_canfd_ops *ops;
	struct sdc_can_platdata *pdata;
	struct platform_device *pdev;
	struct device *dev;

	unsigned long rx_count;
	unsigned long tx_count;
	unsigned long rx_div;
	unsigned long tx_div;
	u32  timestamp;

#ifdef CONFIG_PROC_FS
	struct proc_dir_entry *dev_ent;
#endif

};

struct sdc_canfd_hw_tef_obj {
	u32 flags;
	u32 id;
	u32 ts;
};

#ifndef sizeof_field
#define sizeof_field(TYPE, MEMBER) sizeof((((TYPE *)0)->MEMBER))
#endif

struct __packed sdc_canfd_hw_tx_obj_raw {
	__le32 id;
	__le32 flags;
	u8 data[sizeof_field(struct canfd_frame, data)];
};

struct sdc_canfd_hw_rx_obj_canfd {
	u32 flags;
	u32 id;
	u32 ts;
	u8 data[sizeof_field(struct canfd_frame, data)];
};

#endif
